### ISSUE TITLE
What GSP we can use in this model?

### ISSUE THREAD

**Issue by anjandeveloper** [sujianalytics/gst-e-invoicing-sap#1]
I like to know what are the possible number of GSP that it would support. Also is there any possibility to create a switch the GSP?

**Comment by sujianalytics** [comment]
Hi,

As of now we support two GSP API providers: MastersIndia and ClearTax, but we should also mention that this solution work with all other GSP API Providers which doesn't required multi level encryption.

There is the file which called `api.conf `which can be referred for switching the configuration a real-time.

Thanks
